# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: eyeplus
#   pool: 5
#   username: development
development:
  adapter: sqlite3
  database: db/eyeplus.sqlite3
  pool: 5
  timeout: 5000
  strict: false
